const { withXcodeProject } = require("expo/config-plugins");

// Apple Developer Program team (paid Individual, Team T29NU9NCA2; cert
// "Apple Development: erlin.hx@icloud.com"). Paid membership → 1-year
// provisioning profiles (no more 7-day free-team re-sign ritual).
const DEVELOPMENT_TEAM = "T29NU9NCA2";
const BUNDLE_ID = "xyz.streamarena.spotify";

// Sets the Apple Development team + automatic signing on the app target so that
// `expo run:ios --device` (and any prebuild) produces a device-installable build
// without anyone opening Xcode. mobile/ios is git-ignored / regenerated by
// prebuild, so this plugin is the durable home for the signing config.
module.exports = function withSigning(config) {
  return withXcodeProject(config, (cfg) => {
    const project = cfg.modResults;
    const configs = project.pbxXCBuildConfigurationSection();
    for (const key of Object.keys(configs)) {
      const buildConfig = configs[key];
      const settings = buildConfig && buildConfig.buildSettings;
      if (!settings) continue;
      // Only the app target carries the bundle id; skip Pods/project configs.
      if (settings.PRODUCT_BUNDLE_IDENTIFIER !== BUNDLE_ID) continue;
      settings.DEVELOPMENT_TEAM = DEVELOPMENT_TEAM;
      settings.CODE_SIGN_STYLE = "Automatic";
    }
    return cfg;
  });
};
