import { normalizeStorageKey } from "@/lib/storage-keys";

export type AccountMediaRow = {
  url: string | null;
};

const MANAGED_FILE_PREFIX = "/api/files/";

// Account deletion must never turn an arbitrary URL stored in the database into
// an R2 delete. Only URLs generated by this app's file endpoint are eligible,
// and normalizeStorageKey rejects traversal / malformed keys.
export function managedStorageKeyFromUrl(value: unknown): string | null {
  if (typeof value !== "string") return null;
  const url = value.trim();
  if (!url.startsWith(MANAGED_FILE_PREFIX)) return null;

  const encoded = url.slice(MANAGED_FILE_PREFIX.length).split(/[?#]/, 1)[0] ?? "";
  if (!encoded) return null;
  const decoded = encoded
    .split("/")
    .filter(Boolean)
    .map((part) => {
      try {
        return decodeURIComponent(part);
      } catch {
        return part;
      }
    })
    .join("/");

  try {
    return normalizeStorageKey(decoded);
  } catch {
    return null;
  }
}

export function collectManagedStorageKeys(rows: AccountMediaRow[]): string[] {
  const keys = new Set<string>();
  for (const row of rows) {
    const key = managedStorageKeyFromUrl(row.url);
    if (key) keys.add(key);
  }
  return [...keys];
}

export function exclusiveManagedStorageKeys(
  accountRows: AccountMediaRow[],
  otherAccountRows: AccountMediaRow[],
): string[] {
  const shared = new Set(collectManagedStorageKeys(otherAccountRows));
  return collectManagedStorageKeys(accountRows).filter((key) => !shared.has(key));
}
