import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Providers } from "@/components/Providers";
import { AuthButtons } from "@/components/AuthButtons";
import { PlayerBar } from "@/components/PlayerBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}>
        <Providers>
          <header className="border-b border-black/10 dark:border-white/10">
            <div className="max-w-7xl mx-auto px-6 h-14 flex items-center justify-between">
              <Link href="/" className="font-semibold">Spotify Clone</Link>
              <nav className="flex items-center gap-6">
                <Link href="/" className="opacity-80 hover:opacity-100">Home</Link>
                <Link href="/upload" className="opacity-80 hover:opacity-100">Upload</Link>
                <AuthButtons />
              </nav>
            </div>
          </header>
          <main>{children}</main>
          <PlayerBar />
        </Providers>
      </body>
    </html>
  );
}
